// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddProductLikeController from "./add_product_like_controller"
application.register("add-product-like", AddProductLikeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
